# This file is machine-generated - editing it directly is not advised

[[CubicEoSDatabase]]
deps = ["DelimitedFiles"]
git-tree-sha1 = "2284e6fa8cb2422f377db2a45a8916fbad203707"
repo-rev = "main"
repo-url = "https://github.com/stepanzh/CubicEoSDatabase.jl.git"
uuid = "8742253c-1987-415f-b31d-1ec9670d9ed7"
version = "0.2.3"

[[DelimitedFiles]]
deps = ["Mmap"]
uuid = "8bb1440f-4735-579b-a4ab-409b98df4dab"

[[DescentMethods]]
deps = ["LinearAlgebra"]
git-tree-sha1 = "69c17edf31fe4519283fb0c006cea54278a6d447"
repo-rev = "master"
repo-url = "https://github.com/vvpisarev/DescentMethods.jl"
uuid = "f4becde8-b16e-4b5a-8f91-16ef0c22c8bc"
version = "0.1.0"

[[Libdl]]
uuid = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[[LinearAlgebra]]
deps = ["Libdl"]
uuid = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[[Mmap]]
uuid = "a63ad114-7e13-5084-954f-fe012c677804"
