name = "CubicEoS"
uuid = "0772a1fa-d924-41f2-9f07-889679823dc5"
authors = ["Vasily Pisarev <pisarevvv@phystech.edu>", "Stepan Zakharov <stepan.zakharov@phystech.edu>"]
version = "0.1.0"

[deps]
CubicEoSDatabase = "8742253c-1987-415f-b31d-1ec9670d9ed7"
DescentMethods = "f4becde8-b16e-4b5a-8f91-16ef0c22c8bc"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
CubicEoSDatabase = "0.2.2"
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
